# Generated by Django 5.2 on 2025-06-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_avatar_alter_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_all_profiles', 'Может просматривать все профили пользователей'), ('can_edit_any_profile', 'Может редактировать любой профиль'), ('can_manage_user_roles', 'Может управлять ролями пользователей')], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
