# Generated by Django 5.1.6 on 2025-04-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_tag_comment_photo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
    ]
