# Generated by Django 5.2 on 2025-06-01 15:13

import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемое'),
        ),
        migrations.AddField(
            model_name='photo',
            name='rating',
            field=models.IntegerField(default=0, help_text='Рейтинг от 0 до 10', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='Поддерживаемые форматы: JPG, PNG, GIF. Максимальный размер: 10MB', upload_to=photos.models.generate_unique_filename, verbose_name='Изображение'),
        ),
    ]
