# Generated by Django 5.2 on 2025-06-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_photo_is_featured_photo_rating_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='rating',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name=''),
        ),
    ]
