# Generated by Django 5.1.6 on 2025-06-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_remove_photo_rating_alter_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_featured',
        ),
    ]
